POST http://localhost:4000/app/register
Content-Type: application/json

{
    "fullname": "Narisara",
    "email": "nicknarisara@gmail.com",
    "university": "TU",
    "department": "Comsci",
    "faculty": "sci",
    "studentid": "6109680261",
    "username": "Narisara",
    "password": "123456",
    "confirmpassword": "123456",
    "address": "-" 

}